### PR TITLE
Modify satellite declarative notebook from python-training repo

### PR DESCRIPTION
**Pull request by mgrover1**
In response to #13 
Includes explanation of declarative plotting interface including `PlotObs`, `ImagePlot`, and `ContourPlot`, pulling data using Siphon

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Once the CLA check passes I'll get this in. I'll open another PR to clean out the other notebooks since we have one that's a non-placeholder. Thank you @mgrover1!

**Comment by mgrover1** [comment]
> Once the CLA check passes I'll get this in. I'll open another PR to clean out the other notebooks since we have one that's a non-placeholder. Thank you @mgrover1!

Thanks @lesserwhirls for some reason when I attempt to sign the CLA agreement, a blank page comes up. I know I have signed it before with my account, but for some reason, it is still giving this error.

**Comment by jthielen** [comment]
Also, @mgrover1, just in case you don't get the updates to the python-training repo, it was recently mentioned by @jrleeman in https://github.com/Unidata/python-training/issues/65 that the import conventions for declarative plotting would be changing to `from metpy.plots.declarative import *`. It may be worth updating this notebook as well for consistency (either in this or a follow up PR)?

**Comment by mgrover1** [comment]
> Also, @mgrover1, just in case you don't get the updates to the python-training repo, it was recently mentioned by @jrleeman in [Unidata/python-training#65](https://github.com/Unidata/python-training/issues/65) that the import conventions for declarative plotting would be changing to `from metpy.plots.declarative import *`. It may be worth updating this notebook as well for consistency (either in this or a follow up PR)?

Thanks for the suggestion - I will go ahead and make those changes.

**Pull request closed without merging**
